# Generated by Django 3.2.2 on 2021-05-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210525_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_visible',
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_email',
            field=models.BooleanField(default=True),
        ),
    ]
