# Generated by Django 3.2.2 on 2021-05-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210525_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='hide_email',
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
    ]
