# Generated by Django 3.2.2 on 2021-05-17 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board', models.CharField(default='000000000', max_length=9)),
                ('turn', models.CharField(default='O', max_length=1)),
                ('scoreX', models.IntegerField(default=0)),
                ('scoreO', models.IntegerField(default=0)),
                ('connected', models.ManyToManyField(blank=True, related_name='connected_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('easy', models.IntegerField(default=0)),
                ('moderate', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('unbeatable', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
