# Generated by Django 3.2.2 on 2021-05-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxscore',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ttt_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
